name: Generate space shooter animation

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate-space-shooter-animation
        uses: czl9707/gh-space-shooter@master
        with:
          github_user_name: ${{ github.repository_owner }}
          # The output is a GIF file
          # The resulting file will be available in the 'dist' directory
          # and then pushed to the 'output' branch

      - name: push space-shooter.gif to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
